name: Avg. IoU

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

jobs:
  push_to_hub:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "layout-average-iou"
      DIR_NAME: "layout_average_iou"

      SRC_DIR: ./github-repo
      DST_DIR: ./huggingface-repo

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.SRC_DIR }}

      - name: Checkout Huggingface repository
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          git clone https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/${REPO_NAME} ${DST_DIR}

      - name: Export requirements.txt
        run: |
          pip install poetry
          poetry -C ${SRC_DIR} export -f requirements.txt --output ${DST_DIR}/requirements.txt --without-hashes

      - name: Copy files to Huggingface repository
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_EMAIL: ${{ secrets.HF_EMAIL }}
        run: |
          make deploy REPO_NAME=${REPO_NAME} DIR_NAME=${DIR_NAME}
