name: Push to Hugging Face Space

# on:
#   workflow_run:
#     workflows:
#       - CI
#     branches:
#       - main
#     types:
#       - completed

on: [push]

jobs:
  push_to_hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          path: github-repository

      - name: Checkout Huggingface repository
        uses: actions/checkout@v4
        with:
          repository: spaces/shunk031/layout_alignment
          path: huggingface-repository
          github-server-url: https://huggingface.co
          token: ${{ secrets.HF_TOKEN }}
